// Copyright (c) Athena Dev Teams - Licensed under GNU GPL
// For more information, see LICENCE in the main folder

/**
 * Custom Script Commands
 * Place the definition of custom script commands in this file.
 * Format:
 *	BUILDIN_DEF(command_name,"parameters"),
 **/

//BUILDIN_DEF(example,""),

// [Nerguri] 도작 소스
BUILDIN_DEF(plagiarism, "ii"),
BUILDIN_DEF(get_disidentif_count,""),
BUILDIN_DEF(identify_item,"i"),
